version: '3'

services:
  web:
    networks:
      - app-net
    ports:
      - "18080:8080"
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - db
  bot:
    networks:
      - app-net
    build:
      context: .
      dockerfile: ./docker/bot/Dockerfile
    depends_on:
      - db
      - web
  db:
    networks:
      - app-net
    container_name: db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    env_file: .env
    volumes:
      - ./mysql8_data:/var/lib/mysql

networks:
  app-net:
    driver: bridge
